Fixing this error by using powershell instead of defaulting to cmd
module.panos-bootstrap.null_resource.file_uploads (local-exec): Executing: ["cmd" "/C" "cd ./files; az storage file upload-batch --account-name bootstrapacct44790 --account-key /Hunhca/G2IaJqDubdyUpDWNC3y+lKV25oiIebPUchtuYljSdg6Ah/rdbvrDMGtiqWKDVWDVv33dv9ePxebIVA== --source . --destination bootstrapshare44790"]
module.panos-bootstrap.null_resource.file_uploads (local-exec): The system cannot find the path specified.


Error: Error running command 'cd ./files; az storage file upload-batch --account-name bootstrapacct44790 --account-key /Hunhca/G2IaJqDubdyUpDWNC3y+lKV25oiIebPUchtuYljSdg6Ah/rdbvrDMGtiqWKDVWDVv33dv9ePxebIVA== --source . --destination bootstrapshare44790': exit status 1. Output: The system cannot find the path specified.